- hosts: servers
  sudo: true
  user: vagrant
  tasks:
      #    - name: get nginx repo
      #      get_url: url="http://nginx.org/packages/centos/5/noarch/RPMS/nginx-release-centos-5-0.el5.ngx.noarch.rpm" dest=/etc/yum.repos.d/nginx.repo

   - name: set nginx repo
     command: rpm -ivh http://nginx.org/packages/centos/5/noarch/RPMS/nginx-release-centos-5-0.el5.ngx.noarch.rpm

   - name: install nginx
     yum: name=nginx state=present 

