- hosts: servers
  sudo: true
  user: vagrant
  tasks:
    - name: install zlib zlib-devel memcache
      yum: name={{item}} state=latest
      with_items:
        - zlib
        - zlib-devel
        - memcached

    - name: install memcache  
      command: pecl install memcache

    - name: echo "extension=memcache.so" > /etc/php.d/memcache.ini
      command: echo "extension=memcache.so" > /etc/php.d/memcache.ini
 
