- hosts: servers
  sudo: true
  user: vagrant
  tasks:
    - name: install zlib
      yum: name=zlib state=latest

    - name: install zlib-devel
      yum: name=zlib-devel state=latest

    - name: install memcache
      yum: name=memcache state=latest

    - name: install memcache  
      command: pecl install memcache

    - name: echo "extension=memcache.so" > /etc/php.d/memcache.ini
      command: echo "extension=memcache.so" > /etc/php.d/memcache.ini
 

