- hosts: servers
  sudo: true
  user: vagrant
  tasks:
    - name: remove existing mysql
      yum: name=mysql* state=absent

    - name: install mysql server
      yum: name=http://dev.mysql.com/get/Downloads/MySQL-5.6/MySQL-server-5.6.16-1.el6.x86_64.rpm state=present 

    - name: install mysql client
      yum: name=http://dev.mysql.com/get/Downloads/MySQL-5.6/MySQL-client-5.6.16-1.el6.x86_64.rpm state=present 

    - name: install mysql devel
      yum:  name=http://dev.mysql.com/get/Downloads/MySQL-5.6/MySQL-devel-5.6.16-1.el6.x86_64.rpm state=present 

    - name: install mysql shared
      yum: name=http://dev.mysql.com/get/Downloads/MySQL-5.6/MySQL-shared-5.6.16-1.el6.x86_64.rpm state=present 

    # for ec2
    #- name: install DATA-Dumper
    #  yum: name=perl-Data-Dumper state=latest

    - name: init mysql data directory
      command: mysql_install_db --datadir=/var/lib/mysql/ --user=mysql

